### ISSUE TITLE
LOG_LEVEL has no effect

### ISSUE THREAD

**Issue by dennypage** [crazy-max/docker-rrdcached#3]
As discussed [here](https://github.com/librenms/docker/issues/51), LOG_LEVEL has no effect on rrdcached due to the use of syslog.

Suggest adding "-o /dev/stdout" to rrdcached to redirect logging to the output of the container.

**Comment by crazy-max** [comment]
@dennypage It seems there is no need to add this flag. Logs are duplicated if I add it:

![image](https://user-images.githubusercontent.com/1951866/70308227-125ccd00-180b-11ea-9b1d-98332fbb78c4.png)

**Comment by dennypage** [comment]
Let me look at the code

**Comment by dennypage** [comment]
So I looked at the code. If rrdcached is run in foreground, all output that would be sent to syslog is sent to stderr. Sending it to stdout will indeed duplicate the entire stream from the point of view of the container, so there is no reason for -o as there is no information that we are missing. 

Looking back to the [originating issue](https://github.com/librenms/docker/issues/51), the original premise was wrong. LOG_LEVEL is actually working. The only additional information that the LOG_DEBUG level adds is surrounding journal activity--creating, flushing, rotating. rrdcached as released actually has no facility for logging client requests. It will only log regarding client requests if there are failures reading from the socket, reading information from the rrd file, or writing the response to the socket. Back to square one.
